name: Node.js CI

on: ["push", "pull_request"]
jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:14-alpine

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install python
        run: apk --no-cache add --virtual .builds-deps build-base python2 py3-pip make g++

      - name: Install OS dependencies
        run: apk add --no-cache postgresql-client pkgconfig pixman-dev cairo-dev pango-dev libjpeg-turbo-dev giflib-dev

      - name: Install canvas
        run: yarn add node-canvas-with-twemoji-and-discord-emoji

      - name: Install dependencies
        run: yarn

      - name: Create database
        run: psql -h postgres -d postgres -U postgres -c 'CREATE DATABASE clackbot';
        env:
          PGPASSWORD: postgres

      - name: Migrate database
        run: yarn run knex migrate:latest
        env:
          API_SERVER: http://localhost:5000
          DATABASE_URL: postgres://postgres:postgres@postgres:5432/clackbot

      - name: Run tests
        run: yarn run test
